export const routes = {
  baseRoute: "/",
  classes: "/Class",
  setting: "/Setting",
  register: "/Register",
  login: "/Login",
  parentView: "/Parent",
  programs: "Teacher/Program",
  teacherView: "/Teacher",
  studentView: "/Student",
  classSettings: "/Teacher/Class",
  teacherSubjects: "/Teacher/Subject",
  classAddStudents: "/Teacher/Class/Students/Add",
  classRemoveStudents: "/Teacher/Class/Students/Remove",
  grades: "/Grades",
  addClass: "/Teacher/AddClass",
};
